version: '3.8'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    networks:
      - rsschool
    restart: always

  postgres:
    image: postgres
    env_file:
      - .env
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - rsschool
    volumes:
      - nest-postgres-data:/var/lib/postgresql/data
      - nest-postgres-logs:/var/log/postgresql

networks:
  rsschool:
    driver: bridge

volumes:
  nest-postgres-data:
  nest-postgres-logs:
